version: '3'

services:
  postgres:
    container_name: postgres
    image: 'postgres:9.5'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp
    volumes:
      - './postgres-data:/var/lib/postgresql'
    ports:
      - '5432:5432'


  website:
    container_name: website
    build: .
    volumes:
      - '.:/app'
    ports:
      - '8000:5000'
    depends_on:
      - postgres

volumes:
  db:
